name: document_scanner
description: A new flutter plugin project.
version: 0.0.1
homepage: https://github.com/eliasteeny/flutter_document_scanner

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  
  plugin:
    androidPackage: com.example.document_scanner
    pluginClass: DocumentScannerPlugin

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
